### ISSUE TITLE
Add Yarn support

### ISSUE THREAD

**Issue by sperezm97** [Orbis25/fire-repo#15]
### description
as a react developer we usually use yarn for all the installation file, so that we can manage security strategies level.

it's a pretty easy step. I left you the reference. Also, you are the only one, can do it, because needs the account for npm.

### references
https://classic.yarnpkg.com/lang/en/docs/publishing-a-package

**Comment by Orbis25** [comment]
Link to Yarn package : https://classic.yarnpkg.com/en/package/fire-repo
